name: Log

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-pull:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make docker-pull

  gen-openapi:
    needs: docker-pull
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make gen-openapi
    - run: ls -A ./gen/openapi/opentelemetry/proto
